<a href="https://colab.research.google.com/github/Adithyasajeev22/NLP/blob/main/NLP_BASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TOKENIZATION**

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
print(word_tokenize("This is a Sentence."))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...


['This', 'is', 'a', 'Sentence', '.']


[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


# **REMOVE STOP WORDS**

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt_tab')
text="This is a sample sentence."
words=word_tokenize(text)
print(words)

filtered = [w for w in words if w.lower() not in stopwords.words('english')]
print(filtered)

[nltk_data] Downloading package stopwords to /root/nltk_data...


['This', 'is', 'a', 'sample', 'sentence', '.']
['sample', 'sentence', '.']


[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


# **STEMMING AND LEMMATIZATION**

**STEMMING**

Remov **ing** form

In [ ]:
#STEMMING

from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
print(stemmer.stem("running"))

run


**LEMMATIZATION**

Change the Word in the Base of **Meaning**

In [ ]:
#LEMMATIZATION

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer=WordNetLemmatizer()
print(lemmatizer.lemmatize('running',pos='v'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


run


'v' means verb

'n' means noun (this is the default if you don’t specify pos)

'a' means adjective


In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('wordnet')

stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()

word1="running"
word2="better"
word3="studies"

print("Stemming:")
print(stemmer.stem(word1))
print(stemmer.stem(word2))
print(stemmer.stem(word3))

print("\nLemmatization:")
print(lemmatizer.lemmatize(word1,pos='v'))
print(lemmatizer.lemmatize(word2,pos='a'))
print(lemmatizer.lemmatize(word3,pos='n'))

Stemming:
run
better
studi

Lemmatization:
run
good
study


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


# **POS (Parts O f Speech) Tagging**

In [ ]:
import nltk

#Download the POS tagger data
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt')

from nltk.tokenize import word_tokenize

# Tokenize the sentence
tokens=word_tokenize("This is a Sample Sentence")

# Get POS tags
print(nltk.pos_tag(tokens))

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


[('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('Sample', 'JJ'), ('Sentence', 'NN')]


# **CHUNKING**

In [ ]:
import nltk
text="The quick brown fox jumps over the lazy dog"
tokens=nltk.word_tokenize(text)
tags=nltk.pos_tag(tokens)
chunk_grammer="NP:{<DT>?<JJ>*<NN>}"
cp=nltk.RegexpParser(chunk_grammer)
tree=cp.parse(tags)
tree.pretty_print()

                                     S                                 
     ________________________________|______________________            
    |        |              NP               NP             NP         
    |        |       _______|________        |       _______|______     
jumps/VBZ over/IN The/DT quick/JJ brown/NN fox/NN the/DT lazy/JJ dog/NN



# **NER(Named Entity Recognition)**

In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
doc=nlp("Barack Obama was born in Hawaii.")
print([(ent.text,ent.label_) for ent in doc.ents])

[('Barack Obama', 'PERSON'), ('Hawaii', 'GPE')]


In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
doc=nlp("Apple is looking at buying U.K. startup for $1 billion")
print([(ent.text,ent.label_)for ent in doc.ents])

[('Apple', 'ORG'), ('U.K.', 'GPE'), ('$1 billion', 'MONEY')]


# **WORD EMBEDDING OR VECTORIZATION**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(["This is a sample", "This is another example"])
print(X.toarray())

[[0 0 1 1 1]
 [1 1 1 0 1]]


- Index:   0    1      2      3        4
- Words: ['another', 'example', 'is', 'sample', 'this']

In [ ]:
print(cv.get_feature_names_out())

['another' 'example' 'is' 'sample' 'this']


# **TF-IDF**

- TF = Term Frequency → How often a word appears in a document.

- IDF = Inverse Document Frequency → Measures how important a word is across all documents.

 - Words that appear in many documents get down-weighted.

- TF-IDF = TF × IDF → Higher value means the word is important for that document but rare across others.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X = tf.fit_transform(["This is a sample", "This is another example"])
print(tf.get_feature_names_out())
print(X.toarray())

['another' 'example' 'is' 'sample' 'this']
[[0.         0.         0.50154891 0.70490949 0.50154891]
 [0.57615236 0.57615236 0.40993715 0.         0.40993715]]



[[0.         0.         0.5        0.70710678 0.5       ]
 [0.5        0.5        0.5        0.         0.5       ]]
Row 1: "This is a sample"

'another': 0 (not in doc)

'example': 0 (not in doc)

'is': 0.5 (TF-IDF score)

'sample': 0.7071 (TF-IDF score — more unique!)

'this': 0.5

Row 2: "This is another example"

'another': 0.5

'example': 0.5

'is': 0.5

'sample': 0

'this': 0.5

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["I love NLP"]
cv = CountVectorizer(ngram_range=(1, 3))
X = cv.fit_transform(text)
print(cv.get_feature_names_out())

['love' 'love nlp' 'nlp']



- (1, 1) (default)	Only single words (unigrams)
- (1, 2)	Unigrams and bigrams
- (2, 2)	Only bigrams
- (1, 3)	Unigrams, bigrams, and trigrams

# **SENTIMENT ANALYSIS**

<b>Polarity: 0.5 </b> <br> <hr>
Range: from -1.0 (most negative) to +1.0 (most positive) <br>
Meaning: A value of 0.5 indicates a moderately positive sentiment. <br>
Negative: < 0 <br>
Neutral: 0 <br>
Positive: > 0 <br>
 <b>Subjectivity: 0.6 </b> <br> <hr>
Range: from 0.0 (objective) to 1.0 (subjective)<br>
Meaning: A value of 0.6 suggests the text is fairly subjective, meaning it's based more on personal opinion or feelings than on factual information.


In [ ]:
from textblob import TextBlob
print(TextBlob("I love this product").sentiment)

Sentiment(polarity=0.5, subjectivity=0.6)


| Term             | Simple meaning                     |
| ---------------- | ---------------------------------- |
| **Polarity**     | How negative or positive it is     |
| **Subjectivity** | How much of it is opinion vs. fact |


| Term             | Range                      | Meaning                                      |
| ---------------- | -------------------------- | -------------------------------------------- |
| **Polarity**     | `-1.0` to `+1.0`           | How **negative** or **positive** the text is |
|                  | `-1.0` → Very negative     | Example: *“I hate this movie.”*              |
|                  | `0.0` → Neutral            | Example: *“It is a movie.”*                  |
|                  | `+1.0` → Very positive     | Example: *“I love this movie!”*              |
|                  |                            |                                              |
| **Subjectivity** | `0.0` to `1.0`             | How much is **opinion** vs. **fact**         |
|                  | `0.0` → Completely factual | Example: *“The sun rises in the east.”*      |
|                  | `1.0` → Fully opinionated  | Example: *“I think this is the best ever!”*  |

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#  Example text data (spam detection style)
texts = [
    "Buy now",
    "Limited offer",
    "Call me later",
    "Meeting at noon",
    "Free coupons",
    "Let’s have lunch",
    "Win a prize now",
    "Project discussion tomorrow"
]

labels = [
    "spam",  # Buy now
    "spam",  # Limited offer
    "ham",   # Call me later
    "ham",   # Meeting at noon
    "spam",  # Free coupons
    "ham",   # Let’s have lunch
    "spam",  # Win a prize now
    "ham"    # Project discussion tomorrow
]

#  Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.25, random_state=42
)

#  Create the pipeline
pipe = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])

#  Train the model
pipe.fit(X_train, y_train)

#  Make predictions
preds = pipe.predict(X_test)

#  Evaluate the model
print("Test predictions:", preds)
print("Actual labels:   ", y_test)
print("Accuracy:", accuracy_score(y_test, preds))

#  Try a new example
new_text = ["Congratulations, you won a free ticket!"]
new_pred = pipe.predict(new_text)
print("\nNew text:", new_text[0])
print("Predicted label:", new_pred[0])

Test predictions: ['ham' 'ham']
Actual labels:    ['spam', 'ham']
Accuracy: 0.5

New text: Congratulations, you won a free ticket!
Predicted label: spam
